source:
 db:
  url: jdbc:mysql://192.168.11.14:3306/source
  username: anil
  password: Home@123
  driverName: com.mysql.jdbc.Driver
target:
 db:
  url: jdbc:mysql://192.168.11.14:3306/target
  userName: anil
  password: Home@123
  driverName: com.mysql.jdbc.Driver